### ISSUE TITLE
SDK should support GraphQL

### ISSUE THREAD

**Issue by tcaruth** [oracle/content-management-sdk#5]
I'm imagining a new method on the delivery, preview, and management clients that submit graphQL queries and returns the result as an object
https://docs.oracle.com/en/cloud/paas/content-cloud/solutions/graphql-support-oracle-content-management.html

`/content/preview/api/v1.1/graphql`
`/content/published/api/v1.1/graphql`

```js
await contentClient.graphQL(query, variables)

// returns
{ 
  data: {
    getItem //etc
  }
}
```

**Comment by kmacdonaO** [comment]
Hi Travis, we actually have added a method to the SDK to do this and are preparing to publish it to GitHub.  Here are two examples of usage:

`Examples
// get the id,name,type of all the items in the publishing channel
contentClient.graphql({
    'query': '{ getItems(channelToken: "2834f431f8524ffa89dfb7fe77993284")
 { items { id name type } } }'
}).then(function (response) {
    console.log(response);
});

// get the item slug with the corresponding id in a channel
contentClient.graphql({
    'query': '{ getItem(id:"CORE51A353B7C6AA4EB29C74781FB418C93B",
                        channelToken:"546c6bdfe022455db92741407cccded3")
  { slug } }'
}).then(function (response) {
    console.log(response);
});
`
do you think this will satisfy the requirements that you have?

**Comment by tcaruth** [comment]
Does your method support variables?

**Comment by kmacdonaO** [comment]
Yes, it does support variables - I spent some time today adding tests to validate variable usage.  Usage in my test looks like:
`    const response = await sut.graphql({
      query: 'query ($itemId: ID, $channelToken: String) {getItem(id: $itemId, channelToken: $channelToken) {id}}',
      variables: {
        itemId: process.env.VALID_DIGITAL_ASSET_ID_BASIC,
        channelToken: process.env.CHANNEL_TOKEN_BASIC,
      },
    });`
I have a few other tests to fix up and then I'll publish this to GitHub soon

**Comment by tcaruth** [comment]
Looks good to me. Once it's on GitHub, how long do you think OCM adoption will take?

**Comment by kmacdonaO** [comment]
The package has been published to npmjs now - are you consuming this SDK directly via your OCM service (e.g. for content layouts)?

**Comment by tcaruth** [comment]
Primarily yes, although if there's going to be significant delay for that to be updated we'll import the new version directly



________________________________

**Comment by kmacdonaO** [comment]
We're working to unify the code that is published on the server with the github/npmjs codebase.  The server code is much older though I think it does have a graphql method already which you can probably use.
